# Generated by Django 4.1.1 on 2023-04-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=50, verbose_name='Nombres')),
                ('surnames', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('dni', models.IntegerField(help_text='introduzca su D.N.I. sin puntos', unique=True, verbose_name='dni')),
                ('bitrthday', models.DateField(blank=True, null=True, verbose_name='fecha_de_nacimiento')),
                ('address', models.CharField(max_length=200, verbose_name='domicilio')),
                ('sexo', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], default='male', max_length=10, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
